# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8be2efef03f52c3efbbaa1d30c4591b73f35b44e0a4a7e447183d1e3818e0b6b63eee42636cda51dd9a995fdd36e87696f148ac6b43595cb23ba819cc0063821

test:
  secret_key_base: fe33bf083029c15f97a198bed0b52a07d7fccc723758d025981bdee5a3e916a12c71bd76ae57593ce6f6a0c58432592a7f96a23e1997bcd500e75144937d6968

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
